### ISSUE TITLE
Change / add text about research groups

### ISSUE THREAD

**Issue by MarkRedeman** [ProfessorFrancken/ProfessorFrancken#112]
The research groups page currently contains lorem ipsum text.

[link](http://beta.professorfrancken.nl/study/research-groups ).

The text can be changed [here](https://github.com/ProfessorFrancken/ProfessorFrancken/blob/master/resources/views/study/research-groups/index.blade.php).

**Comment by Sbte** [comment]
Fixed by a4f852
