### ISSUE TITLE
Change / add text on the Francken Vrij page

### ISSUE THREAD

**Issue by MarkRedeman** [ProfessorFrancken/ProfessorFrancken#113]
The [Francken Vrij page](http://beta.professorfrancken.nl/association/francken-vrij) still contains some lorem ipsum text.

It can be changed [here](https://github.com/ProfessorFrancken/ProfessorFrancken/edit/fix-seeding-of-books/resources/views/pages/association/francken-vrij.blade.php).

**Comment by Sbte** [comment]
Fixed by c69d77c
