### ISSUE TITLE
Other Headings for the website

### ISSUE THREAD

**Issue by piet3r** [ProfessorFrancken/ProfessorFrancken#67]
The current Headings of our website are not very efficient/ professional.
About
News
Study
Career
Books
Photos
Contact

There should be a heading for members portal. MY FRANCKEN (or the like)

ABOUT can be called ASSOCIATION
NEWS can be a subsection of ASSOCIATION
BOOKS can be a subsection of STUDY
PHOTOS should be a subsection of the Members portal.

In the Footer there is Contact data. A special heading for contact is a waste of space.
In the Footer data: Contact, there could be a link (MORE CONTACT INFO)  to the contact page

I also have a lot of ideas for the Career page and will make another Issue about this (soon).

**Comment by MarkRedeman** [comment]
Thanks Pieter!
I've added these changes in #71 and published it on the beta website.

> There should be a heading for members portal. MY FRANCKEN (or the like)

Since we haven't started working on the member portal and private photos yet I haven't yet moved this link.

> PHOTOS should be a subsection of the Members portal.

This would have the disadvantage that then *all* photos will be private.

> I also have a lot of ideas for the Career page and will make another Issue about this (soon).

Keep'm coming! :+1:

**Comment by piet3r** [comment]
> This would have the disadvantage that then all photos will be private.
Would this really be a problem? 
Having photo's of yourself online is quite a subjective discussion. Thus better have all photo's behind the login? All Franckenmembers are still able to watch them.

**Comment by MarkRedeman** [comment]
It could be a problem when you have public / joined events with for instance a company or another association. They would probably want to see the photos afterwards. 

This could easily be solved by having a button to download the whole album. Or by having a direct link to each picture which can be shared (this link would be obfuscated so that it wouldn't be easy to find on search engines and such).

**Comment by piet3r** [comment]
Can be closed (?)

**Comment by ProtoPrism** [comment]
Agree, can be closed
