### ISSUE TITLE
Style and user interface

### ISSUE THREAD

**Issue by MarkRedeman** [ProfessorFrancken/ProfessorFrancken#72]
I've made some minor tweaks based on [Francken Vrij 20.1](http://www.professorfrancken.nl/franckenvrij/20.1.pdf). Screenshots below.

Thoughts?

| Mobile | Desktop |
| --------- |:-----------:|
| ![francken-mobile](https://cloud.githubusercontent.com/assets/1114829/19959639/18f66bba-a1a0-11e6-8886-8da379dc8bf6.png) | ![francken-desktop](https://cloud.githubusercontent.com/assets/1114829/19959657/3524848e-a1a0-11e6-9652-93289c5bed3e.png) |

**Comment by ProtoPrism** [comment]
I thinks it looks nice, those Francken Vrij additions. May be the text could be justified as well?

**Comment by piet3r** [comment]
It is more dynamic,
But the board is going to figure out a new house style next month.
So I am curious what they come with.

**Comment by Sbte** [comment]
Closing because there is a new design now
